export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGN_FAIL = 'GET_CAMPAIGN_FAIL';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const DELETE_CAMPAIGN_SUCCESS = 'DELETE_CAMPAIGN_SUCCESS';
export const DELETE_CAMPAIGN_FAIL = 'DELETE_CAMPAIGN_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_DELETING = 'RESET_DELETING';


