export const GET_REWARDS_SUCCESS = 'GET_REWARDS_SUCCESS';
export const GET_REWARDS = 'GET_REWARDS';
export const GET_REWARDS_FAIL = 'GET_REWARDS_FAIL';
export const ADD_REWARD = 'ADD_REWARD';
export const UPDATE_REWARD = 'UPDATE_REWARD';
export const DELETE_REWARD_REQUEST = 'DELETE_REWARD_REQUEST';
export const DELETE_REWARD_SUCCESS = 'DELETE_REWARD_SUCCESS';
export const DELETE_REWARD_FAIL = 'DELETE_REWARD_FAIL';
export const DELETE_REWARD = 'DELETE_REWARD';



