export const CREATE_REWARD = 'CREATE_REWARD';
export const CREATE_REWARD_SUCCESS = 'CREATE_REWARD_SUCCESS';
export const CREATE_REWARD_FAIL = 'CREATE_REWARD_FAIL';
export const UPDATE_REWARD_REQUEST = 'UPDATE_REWARD_REQUEST';
export const UPDATE_REWARD_SUCCESS = 'UPDATE_REWARD_SUCCESS';
export const UPDATE_REWARD_FAIL = 'UPDATE_REWARD_FAIL';

