export const SET_CATEGORIES = 'SET_CATEGORIES';
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_SUCCESS = 'CREATE_CAMPAIGN_SUCCESS';
export const CREATE_CAMPAIGN_FAIL = 'CREATE_CAMPAIGN_FAIL';
export const RESET_CAMPAIGN = 'RESET_CAMPAIGN';
export const RESET_ERRORS = 'RESET_ERRORS';
